baseURL = "/"
languageCode = "en-us"
title = "The Handy Haversack"
relativeurls = false
disableKinds = [ "RSS", "sitemap" ]

[build]
  writeStats = true

[minify]
  minifyOutput = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true